# Generated by Django 5.0.14 on 2026-05-01 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the driver', max_length=255)),
                ('phone', models.CharField(help_text='Primary contact number', max_length=20)),
                ('license_number', models.CharField(help_text='Driving license number', max_length=50, unique=True)),
                ('license_expiry', models.DateField(help_text='License expiry date')),
                ('status', models.CharField(choices=[('available', 'Available'), ('active', 'Active'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The owner (user) this driver belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_driver',
            field=models.OneToOneField(blank=True, help_text='The driver currently assigned to this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='assets.driver'),
        ),
    ]
