# Generated by Django 5.0.14 on 2026-05-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_driver_account_number_driver_ifsc_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('rc', 'RC Book'), ('insurance', 'Insurance'), ('permit', 'Permit'), ('pollution', 'Pollution Certificate'), ('fitness', 'Fitness Certificate'), ('other', 'Other')], max_length=50)),
                ('document_number', models.CharField(help_text='Document identifier (RC number, policy number, etc.)', max_length=100)),
                ('expiry_date', models.DateField()),
                ('file', models.FileField(blank=True, help_text='Uploaded document file (PDF/image)', null=True, upload_to='vehicle_documents/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(help_text='Vehicle this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.vehicle')),
            ],
            options={
                'ordering': ['expiry_date'],
                'unique_together': {('vehicle', 'document_type')},
            },
        ),
    ]
