# Generated by Django 5.0.14 on 2026-05-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_vehicledocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the expense')),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('tax', 'Tax'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='assets.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
